name: Zizmor

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: zizmor-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install zizmor
        run: pipx install zizmor

      - name: Run zizmor
        run: zizmor --pedantic .github/workflows/
